Master:
  Image: "jenkins/jenkins"
  ImageTag: "2.113"
  Component: "master"
  AdminUser: admin
  AdminPassword: admin

  InstallPlugins:
    - kubernetes:1.4.1
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.8.0
    - rebuild:1.28
    - ws-cleanup:0.34
    - lockable-resources:2.2

Persistence:
  Enabled: false

Agent:
  Enabled: false

rbac:
  install: true
  serviceAccountName: default
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: cluster-admin